# The name of the workflow
name: Build and Test

# This workflow will run on any push to the repository
on: push

jobs:
  build:
    # Similar to docker, we set up a virtual machine to run our tests
    runs-on: ubuntu-latest

    steps:
      # Each step has a name, some code, and some options
      - name: Check out the code
        uses: actions/checkout@v3 # This is a reference to some code to run

      - name: Install Homebrew (Linux)
        run: |
          sudo apt update
          sudo apt install -y build-essential curl file git
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo >> /home/runner/.bashrc
          echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> /home/runner/.bashrc
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          sudo brew install nvm

      - name: Verify NVM Installation
        run: |
          nvm --version

    #   - name: Install Dependencies
    #     run: | # Note that there's no reference here — just commands to run
    #       nvm install 20
    #       cd frontend
    #       npm install
    #       cd ../api
    #       npm install
    #       Install MongoDB
    #       brew tap mongodb/brew
    #       brew install mongodb-community@6.0
    #       brew services start mongodb-community@6.0

    #   # Now we run our tests
    #   - name: Test with jest
    #     run: |
    #       cd api
    #       npm run test
