# The name of the workflow
name: Build and Test

# This workflow will run on any push to the repository
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Install Homebrew (Linux)
        run: |
          sudo apt update
          sudo apt install -y build-essential curl file git
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: Add Homebrew to PATH (Linux)
        run: |
          echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> $GITHUB_ENV

      - name: Install NVM (Linux)
        run: |
          brew install nvm

      - name: Load NVM
        run: |
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          echo "NVM_DIR=$NVM_DIR" >> $GITHUB_ENV
          echo "source $NVM_DIR/nvm.sh" >> $GITHUB_ENV

      - name: Verify NVM Installation
        run: |
          source $NVM_DIR/nvm.sh
          nvm --version

      - name: Install Dependencies
        run: |
          source $NVM_DIR/nvm.sh
          nvm install 20
          nvm use 20
          cd frontend
          npm install
          cd ../api
          npm install

      - name: Install and Start MongoDB
        run: |
          brew tap mongodb/brew
          brew install mongodb-community@6.0
          brew services start mongodb-community@6.0

      - name: Test with Jest
        run: |
          cd api
          npm run test
