# The name of the workflow
name: Build and Test

# This workflow will run on any push to the repository
on: push

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Install NVM (macOS)
        run: |
          brew install nvm

      - name: Load NVM
        run: |
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          echo "NVM_DIR=$NVM_DIR" >> $GITHUB_ENV

      - name: Verify NVM Installation
        run: |
          source $NVM_DIR/nvm.sh
          nvm --version

      - name: Install Dependencies
        run: |
          source $NVM_DIR/nvm.sh
          nvm install 20
          nvm use 20
          cd frontend
          npm install
          cd ../api
          npm install

      - name: Install and Start MongoDB (macOS)
        run: |
          brew tap mongodb/brew
          brew install mongodb-community@6.0
          brew services start mongodb/brew/mongodb-community

      - name: Test with Jest
        run: |
          cd api
          npm run test
